#!/bin/bash
#
# Voodoo-Magic
#
#    Voodoo-Magic is free software; you can redistribute it and/or modify it
#    under the terms of the GNU General Public License as published by the Free
#    Software Foundation; either version 2 of the License, or (at your option)
#    any later version.
#
#    Voodoo-Magic is distributed in the hope that it will be useful, but
#    WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
#    or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#    for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with Voodoo-Magic; if not, write to the Free Software Foundation,
#    Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

WORKFLOW_fork() {
    OPTS="$(getopt -n $PROGRAM -o "x:" -l "target:,product:" -- "$@")"
    StopIfError "Unknown argument in workflow: $WORKFLOW"

    eval set -- "$OPTS"
    while true; do
        case "$1" in
            (--target) target=$2; shift;;
            (--product) product=$2; shift;;
            (-x) EXCLUDE_WORKFLOWS+="$2"; shift;;
            (--) shift; break;;
            (-*) Error "Unrecognized option '$option' in workflow: $WORKFLOW";;
            (*) break;;
        esac
        shift
    done

    # the command line argument NAME corresponds to the variable $program
    program="$1"
    [[ -n "$program" ]]
    StopIfError "No name specified"

    # set some default behaviours
    target="${target:-$program}"
    product="${product:-$program}"

    # bail out if targetdir exists and is not empty
    if [[ -d "$target" ]]; then
        ! ls -A "$target"/* >&8
        StopIfError "Target directory exists and is not empty"
    fi

    # bail out if $BASEDIR is / - this leads to recursion!
    [[ ! "$BASEDIR" == '/' ]]
    StopIfError "Basedir not allowed: $BASEDIR == /"

    # mode-select - either regular or git mode
    if $CLONE_GIT; then
        Source "$WORKFLOW_DIR/$WORKFLOW/workflow_git"
    else
        Source "$WORKFLOW_DIR/$WORKFLOW/workflow_regular"
    fi
}

