#!/bin/bash
#
# Voodoo-Magic
#
#    Voodoo-Magic is free software; you can redistribute it and/or modify it
#    under the terms of the GNU General Public License as published by the Free
#    Software Foundation; either version 2 of the License, or (at your option)
#    any later version.
#
#    Voodoo-Magic is distributed in the hope that it will be useful, but
#    WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
#    or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#    for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with Voodoo-Magic; if not, write to the Free Software Foundation,
#    Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

WORKFLOW_fork_DESCRIPTION="Create a new voodoo-magic shell script"
WORKFLOW_fork_USAGE="Usage: $PROGRAM fork NAME [ -x WORKFLOW ; -p PRODUCT ]

Available options:
    -t              - target-directory for the new fork
    -p              - product/brand of the new fork
    -x              - exclude COMMAND from fork

Available commands:
    $(
        find "$SHARE_DIR/workflows/" -mindepth 1 -maxdepth 1 \
            -type d -printf '\t%f\n'
    )
"
WORKFLOW_fork() {
    SourceStage "$WORKFLOW_DIR/$WORKFLOW/functions"

    if $CLONE_GIT; then
        Source "$WORKFLOW_DIR/$WORKFLOW/workflow/git.sh"
    else
        Source "$WORKFLOW_DIR/$WORKFLOW/workflow/regular.sh"
    fi
}

